README

TPM 1.2 is provided in meta-measured but in fact we don't plan to
support it at all.

meta-secure-env: clarify TPM 1.2 feature

---

recipes-kernel/linux-yocto/linux-yocto_%.bbappend

Helios uses linux-yocto instead of linux-yocto-rt.

signing: add the support for linux-yocto

---

recipes-support/efivar/efivar/Multiple-fixes-for-compilation-with-gcc-6.patch
recipes-support/efivar/efivar/Workaround-rename-of-linux-nvme.h.patch
recipes-support/efivar/efivar_0.21.bbappend

The patches ported from upstream resolve the following build failures:
| guid.c: In function 'efi_name_to_guid':
| guid.c:215:6: error: nonnull argument 'name' compared to NULL
[-Werror=nonnull-compare]
|   if (!name || !guid)
|       ^~~~~
| guid.c:215:15: error: nonnull argument 'guid' compared to NULL
[-Werror=nonnull-compare]
|   if (!name || !guid)
|                ^~~~~
and
| linux.c:25:24: fatal error: linux/nvme.h: No such file or directory
|  #include <linux/nvme.h>
|                         ^
| compilation terminated.

efivar-native: fix build failures on Fedora 24

---

recipes-base/packagegroups/packagegroup-storage-encryption.bb
recipes-base/packagegroups/packagegroup-storage-encryption.inc
recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
templates/feature/storage-encryption/README
templates/feature/storage-encryption/storage-encryption.cfg
templates/feature/storage-encryption/storage-encryption.scc
templates/feature/storage-encryption/template.conf

Data volume encryption allows the user to create encryption partition
with a passphrase typed by the end user.
This feature is ported from SCP8, with a big change that we support
TPM 2.0 only.

storage-encryption: support data partition encryption

---

recipes-base/packagegroups/packagegroup-storage-encryption.inc

The package cryptfs-tpm2 is critical for creating LUKS partition for the
storage-encryption feature.

packagegroup-storage-encryption: add the cryptfs-tpm2

---

recipes-base/packagegroups/packagegroup-storage-encryption-initramfs.bb
recipes-core/initrdscripts/files/init.cryptfs
recipes-core/initrdscripts/initramfs-cube-builder.bbappend
recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
templates/feature/storage-encryption/README

This feature is inherited from SCP8 with the following changes:
- Use TPM 2.0 as the secure storage to protect the passphrase.
- The creation process is made in cubeit-installer.

storage-encryption: support rootfs encryption

---

recipes-base/packagegroups/packagegroup-storage-encryption-initramfs.bb

cryptfs-tpm2 is already included in .inc.

packagegroup-storage-encryption-initramfs: remove the duplication

---

recipes-core/initrdscripts/files/init.cryptfs

rm -rf will work without any side effect only when the rootfs mount
point is not specified by the caller. In pulsar runtime, the mount
point is always set and thus the cleanup will wrongly remove the
entire rootfs mount point, leading the failure of mounting the rootfs.
This same issue occurs too with /tmp dir.
To fix this issue, use the safe rmdir.

init.crypt: don't use rm -rf to delete the dir

---

recipes-core/initrdscripts/files/init.cryptfs

If there is no LUKS partition and the first mount attempt fails,
the init.cryptfs is called and the cleanup will wrongly remove
the ROOTFS_DIR where the init script created before calling
init.cryptfs.

Fix boot failure due to wrongly removing mount point for rootfs

---

recipes-core/initrdscripts/files/init.cryptfs
templates/feature/storage-encryption/README

If a non-rootfs LUKS partition was created, the init.cryptfs should stop attempting to mount it.

meta-secure-env: fix boot failure if data encrypted partition exists

---

recipes-bsp/efitools/efitools_git.bb

A _append() function may exit the entire task if returning directly,
which stops other _append() functions running.

efitools: avoid exit the task directly

---

recipes-base/packagegroups/packagegroup-ima-initramfs.bb
recipes-base/packagegroups/packagegroup-ima.bb
recipes-base/packagegroups/packagegroup-ima.inc
recipes-bsp/grub/grub-efi_2.00.bbappend
recipes-core/initrdscripts/files/init.ima
recipes-core/initrdscripts/initramfs-cube-builder.bbappend
recipes-core/util-linux/util-linux_%.bbappend
recipes-support/ima-policy/files/ima_policy.default
recipes-support/ima-policy/ima-policy_0.1.bb
recipes-support/key-store/key-store_0.1.bb
templates/feature/ima/README
templates/feature/ima/template.conf

The Linux IMA subsystem provides the integrity check for the files that
are loaded before it is executed or mmap()ed to memory.
In order to implement IMA in product level, both installation time and
runtime needs to be tuned.
- Installation time
The installer needs to support labeling filesystems to provide the
protections for the executable, shared libraries, kernel modules and
firmwares. This part will be submitted to overc-installer.
- Runtime
* Add "integrity_audit=1 ima_policy=tcb" in kernel commandline.
* The default external policy and public key are loaded in initramfs.
* Provide evmctl tool for IMA signing.

IMA: initial implementation for runtime

---

recipes-support/efivar/efivar/Remove-use-of-deprecated-readdir_r.patch
recipes-support/efivar/efivar_0.21.bbappend

On FC25 with GCC 6.3.1,"-Werror=deprecated-declarations" is default
option, so backport an efivar upstream commit to remove
depreciated variable readdir_r.
This is fixing issue #34 

efivar: Fix build/install error on a host with GCC 6.3.1

---

recipes-bsp/grub/grub-efi_2.00.bbappend

grub-efi: avoid repeatedly appending IMA boot options

---

templates/feature/ima/template.conf
templates/feature/mok-secure-boot/template.conf
templates/feature/storage-encryption/template.conf
templates/feature/tpm/template.conf
templates/feature/tpm2/template.conf
templates/feature/uefi-secure-boot/template.conf
templates/feature/user-key-store-test/template.conf

This is helpful for external logic to know whether certain feature is
enabled or not.

Define DISTRO_FEATURES for each template

---

recipes-support/attr/attr_%.bbappend

setfattr will be used in RPM installation for setting the security.ima.
If we are updating attr package, the dynamically linked setfattr and
libattr cannot be launched. Therefore, introduce the statical version
to run %post hook for each RPM.

attr: build the statically linked setfattr

---

classes/user-key-store.bbclass
recipes-bsp/grub/grub-efi_2.00.bbappend
recipes-core/initrdscripts/initramfs-cube-builder.bbappend
templates/feature/ima/template.conf
templates/feature/mok-secure-boot/template.conf
templates/feature/storage-encryption/template.conf
templates/feature/tpm/template.conf
templates/feature/tpm2/template.conf
templates/feature/uefi-secure-boot/template.conf
templates/feature/user-key-store-test/template.conf

UEFI_SB, MOK_SB and IMA are moved into the interal of UKS, and
STORAGE_ENCRYPTION is dropped.

Clean up the variables used for feature decision

---

recipes-bsp/grub/grub-efi_2.00.bbappend
recipes-core/initrdscripts/initramfs-cube-builder.bbappend

This syntax can cause bitbake failure:
[ test ] &&
command
In order to work around this issue, use if .. then .. fi syntax.

initramfs-cube-builder: fix do_install failure

---

classes/ima.bbclass

If the path of installed file in RPM contains a character requiring
being escaped in shell, e.g, a space, the installation will fail.
The signature list should not use the escaped filename. Otherwise, the
file path in the signature list will be corrupted and points to a
nonexistent place.

IMA: fix RPM installation failure

---

recipes-support/key-store/key-store_0.1.bb
recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb

luks-setup.sh in cryptfs-tpm2 now requires tpm2_takeownership command to
clear TPM 2.0 chip during initialization.

cryptfs-tpm2: add tpm2.0-tools to RDEPEND

---

recipes-core/meta/signing-keys.bbappend

signing-key itself is only used for importing/exporting pubkey on build
host, so it is not required to build it for target.
In addition, fix a typo for the name of private key.

sign-rpm: fix build failure due to rpm signing

---

recipes-core/meta/signing-keys.bbappend

rpm5 always searches gpg2 in higher priority to sign RPM. Hence, if the
signing-keys imports the key with gpg, rpm5 signing will fail for sure
because gpg2 cannot find out the keyring employed by gpg.
This issue only happens if both gpg and gpg2 are installed on a build host.

signing-keys: fix rpm signing failure if both gpg and gpg2 installed

---

recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb

cryptfs-tpm2: update to the latest to contain the fix for tpm2_create

---

recipes-tpm/tpm2.0-tss/tpm2.0-tss/tpm2.0-tss.service
recipes-tpm/tpm2.0-tss/tpm2.0-tss_git.bbappend

So far, we support TPM2.0 service on x86 platform and start TPM2.0
service if there is a file named description in
/sys/class/tpm/tpmX/device. But on arm platform, bsp actions-s500,
this description file is in /sys/class/tpm/tpmX/. So, modify code
to support the 2 platforms.

tpm: improve tpm2.0-tss service to support bsp actions-s500

---

recipes-tpm/trousers/files/tcsd.service
recipes-tpm/trousers/trousers_0.3.13.bbappend

So far, we support tcsd service on x86 platform and start tscd
service if there is a file named caps in /sys/class/tpm/tpmX/device.
But on arm platform, bsp actions-s500, this description file is in
in /sys/class/tpm/tpmX/. So, modify code to support the 2 platforms.

tpm: improve tcsd service to support bsp actions-s500

---

templates/feature/efi-secure-boot/template.conf

GRUB_IMAGE has to been renamed to grub${EFI_ARCH}.efi if MOK Secure
Boot / SELoader is configured. This setting is usually working within
the recipe scope but certain bbclass is not affected and eventually
still uses the wrong naming scheme.
In order to fix this issue, place GRUB_IMAGE into global naming space
and all references to GRUB_IMAGE would sense it.
Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>

mok-secure-boot: setup global GRUB_IMAGE

---

recipes-tpm/openssl-tpm-engine/files/0003-tpm-openssl-tpm-engine-parse-an-encrypted-tpm-SRK-pa.patch
recipes-tpm/openssl-tpm-engine/openssl-tpm-engine_0.4.2.bb

Before, we support reading SRK password from env TPM_SRK_PW,
but it is a plain password and not secure.
So, we improve it and support to get an encrypted (AES algorithm)
SRK password from env, and then parse it. The default decrypting
AES password and salt is set in bb file.
When we initialize TPM, and set a SRK pw, and then we need to
encrypt it with the same AES password and salt by AES algorithm.
At last, we set a env as below:
export TPM_SRK_ENC_PW=xxxxxxxx
"xxxxxxxx" is the encrypted SRK password for libtpm.so.

[v6] tpm:openssl-tpm-engine:parse an encrypted tpm SRK password from env

---

recipes-tpm/openssl-tpm-engine/files/0004-tpm-openssl-tpm-engine-change-variable-c-type-from-c.patch
recipes-tpm/openssl-tpm-engine/openssl-tpm-engine_0.4.2.bb

refer to getopt_long() function definition, its return value type is int.
So, change variable c type from char into int.
On arm platform, when getopt_long() calling fails, if we define c as char
type, its value will be 255, not -1. This will cause code enter wrong case.
@jiazhang0

tpm:openssl-tpm-engine: change variable c type from char into int

---

recipes-tpm/openssl-tpm-engine/files/0005-tpm-openssl-tpm-engine-parse-an-encrypted-TPM-key-pa.patch
recipes-tpm/openssl-tpm-engine/openssl-tpm-engine_0.4.2.bb

when openssl-tpm-engine lib is used on an unattended device, there is no
way to input TPM key password. So add this feature to support parse an
encrypted(AES algorithm) TPM key password from env.
The default decrypting AES password and salt is set in bb file.
When we create a TPM key(TSS format), generate a 8 bytes random data
as its password, and then we need to encrypt the password with the same
AES password and salt in bb file.
At last, we set a env as below:
export TPM_KEY_ENC_PW=xxxxxxxx
"xxxxxxxx" is the encrypted TPM key password for libtpm.so.
@jiazhang0

tpm : openssl-tpm-engine: parse an encrypted TPM key password from env
