- recipes-bsp/shim/shim_git.bb
> shim: update to the latest d3884fe

- recipes-bsp/shim/shim_git.bb
> shim: install shim and Mok manager to deploydir

- recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
> cryptfs-tpm2: update to 0.2.1

- recipes-base/packagegroups/packagegroup-storage-encryption.bb
- recipes-base/packagegroups/packagegroup-storage-encryption.inc
The first commit fixes the missing package issue.
> packagegroup-storage-encryption: 2 commits

- recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
> cryptfs-tpm2: fix commit id

- templates/feature/storage-encryption/README
> storage-encryption: clarify using --encrypt option to create the encrypted rootfs

- recipes-core/initrdscripts/files/init.cryptfs
- recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
> cryptfs-tpm2: update to 0.4.0

- recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
> cryptfs-tpm2: update to 0.4.1

- recipes-bsp/shim/shim_git.bb
This update contains the bug fix for TPM access.
> shim: update to the latest

- recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
> cryptfs-tpm2: update to the latest

- templates/feature/storage-encryption/README
> storage-encryption: add the details about how to access encrypted data partition

- recipes-bsp/efitools/efitools/LockDown-show-the-error-message-with-3-sec-timeout.patch
- recipes-bsp/efitools/efitools_git.bb
> efitools/LockDown: show the error message with 3-sec timeout

- classes/user-key-store.bbclass
- templates/feature/user-key-store-test/README
> IMA: support to automatically generate user key for IMA signing

- recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
> cryptfs-tpm2: sync up with the latest upstream

- README
> README: document the feature description about storage-encryption

- classes/user-key-store.bbclass
- conf/layer.conf
- recipes-bsp/efitools/efitools/Makefile-do-not-build-signed-efi-image.patch
- recipes-bsp/efitools/efitools_git.bb
- recipes-bsp/shim/shim/Makefile-do-not-sign-the-efi-file.patch
- recipes-bsp/shim/shim_git.bb
- templates/feature/user-key-store-test/template.conf
We need to make some adaption to support EDSS on meta-secure-env layer, however, EDSS implamentation will be pulsar-binary-release layer.
> Adaption to support EDSS

- classes/ima.bbclass
- recipes-base/packagegroups/packagegroup-ima.bb
- recipes-support/ima-evm-utils/ima-evm-utils_git.bbappend
- templates/feature/ima/template.conf
When the files are updated, the content of xattr based on digital
signature needs to be re-signed.
> IMA: hook %post

- recipes-base/packagegroups/packagegroup-ima.bb
- templates/feature/ima/README
> IMA: document an known issue if overwriting a file with the same content

- README
> README: trivial cleanup

- classes/ima.bbclass
- templates/feature/storage-encryption/template.conf
> ima.bbclass: trivial cleanup

- recipes-base/packagegroups/packagegroup-ima.bb
> packagegroup-ima: fix a typo

- classes/ima.bbclass
The symbol links should be omitted during the signing. We do it earlier
to avoid checking it in runtime.
> IMA: fix RPM installation failure

- classes/user-key-store.bbclass
- recipes-tpm/cryptfs-tpm2/cryptfs-tpm2_git.bb
> user-key-store: code cleanup

- recipes-core/meta/signing-keys.bbappend
This will not contaminate build host's keyring. If GPG_PATH is not configured, a default value will be set as "${DEPLOY_DIR_IMAGE}/.gnupg"
> signing-keys: add gpg home directory support

- recipes-core/meta/signing-keys.bbappend
> signing-keys: depends on native gnupg

- recipes-core/meta/signing-keys.bbappend
> signing-keys: fix a dependency typo

- recipes-core/meta/signing-keys.bbappend
> signing-keys: populate native rpm before importing gpg pubkey

- conf/layer.conf
Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
> layer.conf: add LAYERDEPENDS

- templates/feature/ima/require
- templates/feature/ima/template.conf
- templates/feature/mok-secure-boot/require
- templates/feature/mok-secure-boot/template.conf
- templates/feature/msft/require
- templates/feature/storage-encryption/require
- templates/feature/storage-encryption/template.conf
- templates/feature/tpm2/require
- templates/feature/tpm2/template.conf
Fix warning "Duplicate inclusion for xxx/template.conf ..."
Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>
> templates: add require
